/**
 * 
 * File Type constants used to passed into the File Factory to get Appropriate FileWriter FileReader Class Instance
 * 
 */
package som.constants;

/**
 * @author prashant
 *
 */
public interface IFileFactoryConstants {
  
	String UNIT_VECTOR_FILE = "UNIT_VECTOR_FILE";
	String WEIGHT_VECTOR_FILE = "WEIGHT_VECTOR_FILE";
	String DWM_FILE = "DWM_FILE";
	String INPUT_VECTOR_FILE = "INPUT_VECTOR_FILE";
	String TEMPLATE_VECTOR_FILE = "TEMPLATE_VECTOR_FILE";
	String BEST_WORDS_TEMPLATE_VECTOR_FILE = "BEST_WORDS_TEMPLATE_VECTOR_FILE";
	String CUSTOM_SOM_OUTPUT_FILE = "CUSTOM_SOM_OUTPUT_FILE";
	String CUSTOM_SOM_PARSER_UNIT_OUTPUT_FILE = "CUSTOM_SOM_PARSER_UNIT_OUTPUT_FILE";
	String BEST_WORDS_FILE = "BEST_WORDS_FILE";
	String VISUAL_DATA_JSON_FILE_WRITER = "VISUAL_DATA_JSON_FILE_WRITER";
	String DWM_FILE_READER = "DWM_FILE_READER";
	String BEST_WORDS_FILE_GENERATOR = "BEST_WORDS_FILE_GENERATOR";



}